#!/bin/bash
 
xsetroot -cursor_name left_ptr
sxhkd &

pkill picom
picom -f --daemon --config "${HOME}/.config/picom/picom.conf" &
wmname LG3D &
feh --bg-fill ~/Downloads/bg-csm-power.png &
polybar &

bspc config border_width	1
bspc config window_gap		3 

bspc config left_padding 5
bspc config right_padding 5
bspc config bottom_padding 10

bspc config split_ratio		0.50
bspc config focus_follows_pointer	true
bspc config pointer_modifier	mod1
 
bspc config automatic_scheme	spiral

bspc monitor -d I II III IV V VI VII VIII IX X

